// Code generated by whyor. DO NOT EDIT.

//go:build !whyor

package edge

import (
	log "github.com/medzoner/whyor/examples/edge/a/log"
	log2 "github.com/medzoner/whyor/examples/edge/b/log"
	time "time"
)

func InitOut() (Out, func(), error) {
	v1 := 5 * time.Second
	v2 := "edge"
	v3 := log.New()
	v4 := log2.New()
	v5, cleanup5 := NewR1()
	v6, cleanup6 := NewR2(v5)
	v7, cleanup7, err := NewR3(v6)
	if err != nil {
		cleanup6()
		cleanup5()
		return *new(Out), nil, err
	}
	v8 := NewOut(v1, v2, v3, v4, v7)
	return v8, func() {
		cleanup7()
		cleanup6()
		cleanup5()
	}, nil
}
