// Code generated by whyor. DO NOT EDIT.

//go:build !whyor

package main

func InitApp(name string) (*App, func(), error) {
	v1 := NewConfig(name)
	v2, cleanup2, err := NewStore(v1)
	if err != nil {
		return nil, nil, err
	}
	v3 := NewApp(v2)
	return v3, func() {
		cleanup2()
	}, nil
}
