// Code generated by whyor. DO NOT EDIT.

//go:build !whyor

package lifecycle

import (
	context "context"
	errors "errors"
	whyor "github.com/Medzoner/whyor"
)

func InitApp(ctx context.Context, events *Events) (*App, whyor.Cleanup, error) {
	v1, cleanup1 := NewLegacy(events)
	v2, cleanup2 := NewCache(ctx, v1, events)
	v3 := NewSocket(v2, events)
	v4, err := NewApp(v1, v2, v3, events)
	if err != nil {
		err = errors.Join(err, v3.Close())
		err = errors.Join(err, cleanup2(context.WithoutCancel(ctx)))
		cleanup1()
		return nil, nil, err
	}
	return v4, func(_cleanupCtx context.Context) error {
		var err error
		err = errors.Join(err, v3.Close())
		err = errors.Join(err, cleanup2(_cleanupCtx))
		cleanup1()
		return err
	}, nil
}

func InitDetached(events *Events) (*App, func(context.Context) error, error) {
	v1, cleanup1 := NewDetached(events)
	v2, err := NewFailed(v1)
	if err != nil {
		err = errors.Join(err, cleanup1(context.Background()))
		return nil, nil, err
	}
	return v2, func(_cleanupCtx context.Context) error {
		var err error
		err = errors.Join(err, cleanup1(_cleanupCtx))
		return err
	}, nil
}

func InitLegacy(events *Events) (*Legacy, whyor.Cleanup) {
	v1, cleanup1 := NewLegacy(events)
	return v1, func(_cleanupCtx context.Context) error {
		var err error
		cleanup1()
		return err
	}
}

func InitEmpty() (*App, whyor.Cleanup) {
	v1 := &App{}
	return v1, func(_cleanupCtx context.Context) error {
		var err error
		return err
	}
}
