// Code generated by whyor. DO NOT EDIT.

//go:build !whyor

package typeidentity

func InitResult(p struct{ Value Number }) Result {
	v1 := NewTransform()
	v2 := NewOptions()
	v3 := NewReader()
	v4 := NewBox()
	v5 := NewResult(v1, v2, v3, v4, p, v1)
	return v5
}

func InitBox() (*Box[int], func()) {
	v1 := NewBox()
	return v1, func() {
		v1.Close()
	}
}

func InitBoxes() []*Box[int] {
	v1 := NewBox()
	v2 := []*Box[Number]{v1}
	return v2
}
