// Code generated by whyor. DO NOT EDIT.

//go:build !whyor

package features

func InitServer(log *[]string) (*Server, func()) {
	v1 := NewUsers()
	v2 := NewOrders()
	v3 := []Handler{v1, v2}
	v4 := NewRouter(v3)
	v5 := NewCache(log)
	v6 := NewServer(v4, v5, v1)
	return v6, func() {
		_ = v5.Close()
	}
}
