// Code generated by whyor. DO NOT EDIT.

//go:build !whyor

package generics

import (
	providers "github.com/Medzoner/whyor/examples/generics/providers"
)

func InitApp(user User, order Order, events *providers.Events) (*App, func(), error) {
	v1, cleanup1, err := providers.NewRepository[User](user, events)
	if err != nil {
		return nil, nil, err
	}
	v2, cleanup2, err := providers.NewRepository[Order](order, events)
	if err != nil {
		cleanup1()
		return nil, nil, err
	}
	v3 := providers.NewLabel[User]()
	v4 := providers.NewLabel[Order]()
	v5 := []providers.Label{v3, v4, v3}
	v6 := providers.NewPair[User, Order](user, order)
	v7 := NewApp(v1, v2, v5, v3, v6)
	return v7, func() {
		cleanup2()
		cleanup1()
	}, nil
}
