// Code generated by whyor. DO NOT EDIT.

//go:build !whyor

package basic

func InitApp(dsn string) (*App, func(), error) {
	v1 := NewConfig(dsn)
	v2, cleanup2, err := NewPG(v1)
	if err != nil {
		return nil, nil, err
	}
	v3 := NewApp(v2)
	return v3, func() {
		cleanup2()
	}, nil
}
